### ISSUE TITLE
Links插件启动后设置出错

### ISSUE THREAD

**Issue by Part01-Pai** [bakaomg/NekoLinks#6]
之前单独编辑过links独立页面，Links插件启动时出错，进入设置时“检测到您的安装过 Links 插件，并且留存有友链数据，您是否想将 Links 的数据迁移到 NekoLinks ？”，不再提示和迁移都报错，我查过数据库并没有相关表qwq

**Comment by bakaomg** [comment]
F12打开浏览器控制台，访问友链设置页面，点击迁移或者不再提醒，然后查看 API 请求，把具体返回提供下（
例如：
![image](https://user-images.githubusercontent.com/40896676/230223591-efced5e3-c79b-407a-9336-4d921192d0ac.png)
![image](https://user-images.githubusercontent.com/40896676/230223825-7140515b-413c-46c2-8273-ff542cf52672.png)

然后需要提供下 PHP 版本、数据库是用的什么，以及 Typecho 版本qwq

**Comment by Part01-Pai** [comment]
![图片](https://user-images.githubusercontent.com/45894602/230768214-2394e4da-1cfb-41b5-81b4-2249e22e9ddf.png)

宝塔面板搭建，PHP 7.4 或 8.1，typecho 1.2.0，Mysql 数据库

**Comment by bakaomg** [comment]
404的话 大概率是伪静态出问题了
检查 Typecho 后台的 `设置` → `永久链接` 中的 `地址重写` 是否开启，以及是否正确配置站点伪静态

**Comment by Part01-Pai** [comment]
> 404的话 大概率是伪静态出问题了 检查 Typecho 后台的 `设置` → `永久链接` 中的 `地址重写` 是否开启，以及是否正确配置站点伪静态

啊哈，我把地址重写和伪静态开了就可以啦，谢谢啦

**Comment by bakaomg** [comment]
好耶 (o゜▽゜)o☆
